### ISSUE TITLE
Document for MetasitoryContainer is missing

### ISSUE THREAD

**Issue by ba0f3** [brooth/jeta#1]
I followed the userguide but there is an error at runtime: Failed to load class com.example.MetasitoryContainer

I did some search but no idea how to make it works

**Comment by brooth** [comment]
You need to generate all the metacode first. Run `gradle assemble` in order to

**Comment by ba0f3** [comment]
thank you for quick reply. I saw it generated w/ `gradle assemble`, but it seems not working w/ IDE.
I'm using Jetbrains' Intellij IDEA

**Comment by ba0f3** [comment]
oh it's very simple, just execute & debug `run` task

thank you for these great works!
