### ISSUE TITLE
Default Metasitory implementation has performance flaws

### ISSUE THREAD

**Issue by Alexander--** [brooth/jeta#3]
Using `*.class` constants in MapMetasitory triggers eager loading of those classes <s>(including invocation of static initializers)</s>. Classloading is slow and triggering too much of it early is a major anti-pattern. Square (creators of Dagger) stumbled upon the issue of excess classloading in Dagger 1, which was combining moderate use of reflection with APT. That caused some Dagger contributors to become so deeply disillusioned with whole thing, that they created Dagger 2, which forces it's users to write names of not-yet-generated classes in code (which IMO is a bit too much).

A possible workaround is to map _class names_ to constructors instead:

``` Java
private static getMetacodeInner(String className) {
    switch(className) {
        case "com.example.HelloWorld":
            return new HelloWorldMetacode();
         case "com.example.SomeOtherClass":
            return new SomeOtherClassMetacode();
        default:
            return null;
    }
}
```

This approach is still Proguard-friendly and does not cause excess classloading in any modern JVMs. In addition it avoids creation of an unnecessary map (especially since all required information is already available at compile time).

**Comment by brooth** [comment]
The only static classloading that takes place is when `MapMetasitory` loads a `MapMetasitoryContainer`. These containers have the similar structure as yours, i.e. create metacode via `new` operator. Nevertheless, since version 2.1 (not released yet) you can escape this loading as well and pass the container instances (as well as in dagger 2 - create not-yet-generated objects) into `MapMetasitory` constructor. Which is also Proguard-friendly.
On the third hand, you always have the option to create any kind of metasitory that you want. Please, refer [this page](http://jeta.brooth.org/guide/custom-metasitory.html) for details.

> unnecessary map

It is necessary since Jeta allows you to search metacode not only by master's class name (as in your example) but by annotations they use as well and other [criterias](http://jeta.brooth.org/guide/at-runtime.html). So it's needed to hold all the meta data in a map to be able to search through.
It is worth noting that the map is `IdentityHashMap` and as the key is used the master's class, so it's very fast to search metacode by the master since it is the most common case.

**Comment by Alexander--** [comment]
You have misunderstood the issue. This is not about avoiding reflection. This is not about avoiding `Class#forName`. You are triggering _classloading_ by referencing the class in code. You code references numerous classes when you populate a map with metadata. Referencing classes by themselves causes them to be loaded. <s>Imagine, that each of those classes has an expensive static initializer or traditional static singleton:

``` Java
public final class HeavyClass {
    static {
        System.loadLibrary("freetype");
        System.loadLibrary("pango");
        System.loadLibrary("xml");
        System.loadLibrary("webkit");
    }

    public static final LazySingleton instance = new LazySingleton();

    public static final class LazySingleton {
        private LazySingleton() {
            // the code below does so much work, you'd rather want
            // to load this class in background thread
            ...
        }
    }
}
```

</s>

It may sound like I am blowing the issue out of proportion (not using lazy initialization should solve it, right?), but the actual classloading: verifying the class in JIT compiler, allocating memory for code etc. — is expensive by itself too. And doing a lot of it early means, that you grab more resources earlier, even if the user ends up using 2% of app.

With the approach I described you should still be able to search by metadata (given that said metadata is carefully stored in strings without referencing involved classes). Referencing the class in branch, that does not run, will not cause it to be loaded. Right now you are always referencing all classes early on during population of your Map.

**Comment by brooth** [comment]
Holding metacode and searching through it doesn't initialize any static stuff since it manipulates `X.class` only. Here is a snippet of `MapMetasitoryContainer`:

``` java
Map<Class<?>, MapMetasitoryContainer.Context> result = new IdentityHashMap<>();
    result.put(com.example.MainActivity.class,
        new MapMetasitoryContainer.Context(
            com.example.MainActivity.class,
            new org.brooth.jeta.Provider<com.example.MainActivity_Metacode>() {
                public com.example.MainActivity_Metacode get() {
                    return new com.example.MainActivity_Metacode();
            }},
            new Class[] {
                org.brooth.androjeta.retain.Retain.class,
                org.brooth.jeta.log.Log.class,
                org.brooth.androjeta.ui.FindView.class,
                org.brooth.jeta.eventbus.Subscribe.class
            }));
```

> You are triggering classloading by referencing the class in code

Here is the sample I've just checked:

``` java
public class StaticHolder {
    static {
        System.out.println("StaticHolder.static");
    }

    static void boo() {
        System.out.println("StaticHolder.boo");
    }
}
```

``` java
public class TestApp {

    static {
        System.out.println("TestApp.static");
    }

    public static void main(String[] args) {
        System.out.println("start");

        StaticHolder.class.equals(TestApp.class);
        StaticHolder.class.hashCode();
        if(StaticHolder.class == null)
            ;

        System.out.println("mid");

        StaticHolder.boo();

        System.out.println("finish");
    }
}

```

Here is the output:

``` bash
TestApp.static
start
mid
StaticHolder.static
StaticHolder.boo
finish
```

Please, let me know if there is a misunderstanding here though

**Comment by Alexander--** [comment]
All right, I was factually wrong: referencing class literal in code apparently does not trigger _static initialization_, since those are apparently neither constants (which is understandable) nor final variables. The language spec does not really elaborate on how they are supposed to work.

Referencing class literals still does trigger classloading, so the main point if this issue still applies.
